//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Bid { get; set; }
        public string Bfrom { get; set; }
        public string Bto { get; set; }
        public string Bcid { get; set; }
        public string Bvno { get; set; }
        public System.DateTime Bdate { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
